### ISSUE TITLE
SEO - Mise en place des meta tags de référencement sur le site web

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#349]
- [ ] Mettre en place les balises META
- [ ] Prévoir les balises OG pour les partages sur les réseaux sociaux
- [ ] Faire un robot.txt

Toutes suggestions sont les bienvenues Pierre : n'hésite pas à proposer ce que tu connais comme solution SEO.

**Comment by guillaumecauchois** [comment]
Resolved and merged
